# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# KPIit is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

dist: trusty

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - redis
  - rabbitmq

env:
  matrix:
    - REQUIREMENTS=prod
    - REQUIREMENTS=qa

python:
  - "3.6"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "cat requirements.txt > .travis-prod-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-qa-requirements.txt"
  - "./scripts/bootstrap"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install .[all]"

script:
  - ./run-tests.sh

after_success:
  - coveralls
